[package]
name = "onqueue"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tiny_http = "0.12.0"
url = "2.5.4"

